### ISSUE TITLE
Too much vanilla

### ISSUE THREAD

**Issue by jolfe** [Psapocalypse/Javascript-Game#1]
# TODO: 
- [ ] add unnecessary libs (p5.js)
- [ ] don't deviate from snake case in your root styles file `#enemy_spider-big` :( 
- [ ] refactor this into Scala
